# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'image_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12image_stream.proto\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x1e\n\rImageResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x32\x45\n\x12ImageStreamService\x12/\n\x0cStreamImages\x12\r.ImageRequest\x1a\x0e.ImageResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=22
  _globals['_IMAGEREQUEST']._serialized_end=51
  _globals['_IMAGERESPONSE']._serialized_start=53
  _globals['_IMAGERESPONSE']._serialized_end=83
  _globals['_IMAGESTREAMSERVICE']._serialized_start=85
  _globals['_IMAGESTREAMSERVICE']._serialized_end=154
# @@protoc_insertion_point(module_scope)
